In [4]:
# 넘파이 1
import numpy as np

In [6]:
# 2
print("NumPy Version:", np.__version__)

np.show_config()

NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

In [7]:
# 3
import numpy as np

null_vector = np.zeros(10)

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
# 4
import numpy as np

vector = np.zeros(10)
vector[4] = 1

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
# 5
import numpy as np

vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# 6
import numpy as np

vector = np.arange(10)
reversed_vector = vector[::-1]

print(reversed_vector)

[9 8 7 6 5 4 3 2 1 0]


In [11]:
# 7
import numpy as np
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# 8
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4]),)


In [13]:
# 9
import numpy as np

identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# 10
import numpy as np

random_array = np.random.random((3, 3, 3))

print(random_array)

[[[0.69069651 0.1473867  0.51580921]
  [0.90629423 0.11801886 0.52211727]
  [0.78754777 0.12497847 0.74046592]]

 [[0.12340774 0.01580246 0.20509508]
  [0.51358082 0.35363391 0.85557831]
  [0.22263563 0.98869552 0.24894955]]

 [[0.13500417 0.61023961 0.77139837]
  [0.94252368 0.30875111 0.65591633]
  [0.75805506 0.36444734 0.93321439]]]


In [15]:
# 11
import numpy as np

random_array = np.random.random((10, 10))
min_value = random_array.min()
max_value = random_array.max()

print(min_value, max_value)

0.011315928981687318 0.9985664451215376


In [16]:
# 12
import numpy as np

random_vector = np.random.random(30)
mean_value = random_vector.mean()

print(mean_value)

0.4497874720404996


In [17]:
# 13
import numpy as np

array = np.ones((10, 10))
array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
# 14
import numpy as np

array = np.ones((5, 5))

bordered_array = np.zeros((array.shape[0] + 2, array.shape[1] + 2))
bordered_array[1:-1, 1:-1] = array

print("Before:")
print(array)
print("\nAfter:")
print(bordered_array)

Before:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

After:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [19]:
# 15
import numpy as np

result_1 = 0 * np.nan
print(result_1)

result_2 = np.nan == np.nan
print(result_2)

result_3 = np.inf > np.nan
print(result_3)

result_4 = np.nan - np.nan
print(result_4)

result_5 = np.nan in set([np.nan])
print(result_5)

result_6 = 0.3 == 3 * 0.1
print(result_6)

nan
False
False
nan
True
False


In [20]:
# 16
import numpy as np

matrix = np.random.random((5, 5))
mean = matrix.mean()
std = matrix.std()

normalized_matrix = (matrix - mean) / std

print(normalized_matrix)

[[-0.71490451 -0.02369973 -1.19318269  1.11507436  2.08814848]
 [-0.76895921 -0.27890504  0.11397055  2.01769789 -0.91004514]
 [ 0.82123647 -0.02678555 -0.86448767  0.88139939 -0.97814867]
 [ 0.71605968 -1.48838654  0.80865106 -0.95379278  0.65258751]
 [-0.18559409  0.03839736 -0.77507978 -1.34274689  1.25149553]]


In [21]:
# 17
import numpy as np

matrix_a = np.random.random((5, 3))
matrix_b = np.random.random((3, 2))
result = np.dot(matrix_a, matrix_b)

print(result)

[[0.69712111 0.84655013]
 [0.54021757 0.76142843]
 [0.52105123 0.71045371]
 [0.54727643 0.5636818 ]
 [0.40268297 0.48045093]]


In [22]:
# 18
import numpy as np

result_1 = np.array(0) / np.array(0)
print(result_1)

result_2 = np.array(0) // np.array(0)
print(result_2)

result_3 = np.array([np.nan]).astype(int).astype(float)
print(result_3)

nan
0
[-9.22337204e+18]


<ipython-input-22-0d6546082b26>:4: RuntimeWarning: invalid value encountered in divide
  result_1 = np.array(0) / np.array(0)
<ipython-input-22-0d6546082b26>:7: RuntimeWarning: divide by zero encountered in floor_divide
  result_2 = np.array(0) // np.array(0)
<ipython-input-22-0d6546082b26>:10: RuntimeWarning: invalid value encountered in cast
  result_3 = np.array([np.nan]).astype(int).astype(float)


In [23]:
# 19
import numpy as np

matrix = np.tile(np.arange(5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [24]:
# 20
import numpy as np

random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)

print(sorted_vector)

[0.01229718 0.10382126 0.18887105 0.20004275 0.20353413 0.29417026
 0.54389424 0.60382017 0.89582429 0.92605022]


In [25]:
# 판다스 1
import pandas as pd

In [26]:
# 2
import pandas as pd

# Print the pandas version
print(pd.__version__)

2.2.2


In [28]:
# 3
import pandas as pd
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


In [29]:
# 4
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [30]:
# 5
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [31]:
# 6
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [32]:
# 7
df[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [33]:
# 8
df.loc[['d', 'e', 'i'], ['animal', 'age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [34]:
# 9
df[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

In [36]:
# 10
df[df['age'].isna()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [37]:
# 11
df[(df['animal'] == 'cat') & (df['age'] < 3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [38]:
# 12
df[(df['age'] >= 2) & (df['age'] <= 4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [39]:
# 13
df.loc['f', 'age'] = 1.5

In [40]:
# 14
total_visits = df['visits'].sum()

In [41]:
# 15
mean_age_per_animal = df.groupby('animal')['age'].mean()

In [42]:
# 16
df.loc['k'] = ['rabbit', 3.2, 4, 'yes']

In [43]:
# 17
animal_counts = df['animal'].value_counts()

In [44]:
# 18
df_sorted = df.sort_values(by=['age', 'visits'], ascending=[False, True])

In [45]:
# 19
df['priority'] = df['priority'].map({'yes': True, 'no': False})

In [46]:
# 20
df['animal'] = df['animal'].replace('snake', 'python')

In [47]:
# 21
np.random.seed(2025)

df = pd.DataFrame(np.random.random(size=(5, 3)))
df = df.subtract(df.mean(axis=1), axis=0)

print(df)

          0         1         2
0 -0.516494  0.235870  0.280624
1  0.081768  0.024435 -0.106204
2 -0.047373 -0.212124  0.259497
3  0.115235 -0.230544  0.115309
4 -0.229731  0.498009 -0.268278
